sudo: required

language: nodejs

services:
  - docker

before_install:
  - docker pull laardee/serverless:1.26.0

script:
  - docker run -e BUCKET=$BUCKET -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/src laardee/serverless:1.26.0 /bin/sh -c "cd src && npm install && npm run package"
