sudo: required

language: nodejs

services:
  - docker

before_install:
- docker pull laardee/serverless

script:
- docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/src laardee/serverless /bin/sh -c "sls package"
